version: '3'
services:
  #  spring1:
  #    container_name: spring1
  #    build: ./
  #    environment:
  #      #      SERVER_PORT: 8080
  #      #      OTEL_SERVICE_NAME: "HelloWorld"
  #
  #      OTEL_METRICS_EXPORTER: "prometheus"
  #      OTEL_EXPORTER_PROMETHEUS_PORT: "9464"
  #
  #      OTEL_LOGS_EXPORTER: "otlp"
  #      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "http://localhost:4320/"
  #
  #      OTEL_TRACES_EXPORTER: "otlp"
  #      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://localhost:4320/"
  #
  #
  #    #      OTEL_SERVICE_NAME: "HelloWorld"
  #    #      OTEL_LOGS_EXPORTER: "otlp"
  #    #      OTEL_EXPORTER_OTLP_ENDPOINT: ""
  #    ports:
  #      - "8080:8080"
  #      - "9464:9464"
  #    depends_on:
  #      - postgres

  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"